# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_beejoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtype',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
        migrations.AlterField(
            model_name='designtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='good',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 7, 20, 7, 583090, tzinfo=utc)),
        ),
    ]
