# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_beejoo', '0002_auto_20161206_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_sum', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='preview_img_uri',
            new_name='img_second_uri',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='full_img_uri',
            new_name='img_uri',
        ),
        migrations.AlterField(
            model_name='good',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 17, 46, 56, 632273, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='order',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonic_beejoo.Good'),
        ),
    ]
