# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_beejoo', '0004_auto_20161208_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(default='test_slug'),
        ),
        migrations.AlterField(
            model_name='good',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 8, 50, 21, 368873, tzinfo=utc)),
        ),
    ]
