# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_beejoo', '0005_auto_20161208_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 8, 52, 29, 582328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
