# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_beejoo', '0006_auto_20161208_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 16, 21, 59, 831283, tzinfo=utc)),
        ),
    ]
